package com.egadwys.gi_employee.payroll.detail

data class DataClass_detail(
    val id: String,
    val periode: String,
    val nik: String,
    val up: String,
    val abs: String,
    val nilai: String,
    val jumlahup: String,
    val jumlahkerja: String,
    val tunjjab: String,
    val tunjmk: String,
    val tunjket: String,
    val tunjutility: String,
    val shift2: String,
    val amtshift2: String,
    val shift3: String,
    val amtshift3: String,
    val ot1: String,
    val amtot1: String,
    val ot2: String,
    val amtot2: String,
    val ot3: String,
    val amtot3: String,
    val ot4: String,
    val amtot4: String,
    val pendapatan: String,
    val bpjstk: String,
    val bpjsks: String,
    val amtabs: String,
    val lain: String,
    val total: String,
    val transfer: String,
    val tunai: String,
    val koperasi: String,
    val kasbongj: String,
    val thk: String,
    val percent: String,
    val mskhe: String,
    val mskeff:String,
    val potongan: String
)
